# --- FONT ---
font_family      Adwaita Mono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0

# --- WINDOW LAYOUT ---
window_padding_width 10
hide_window_decorations yes
placement_strategy top-left

# --- COLORS (Monochrome + Orange-Hued Black Accent) ---
background #000000
foreground #ffffff

# The orange-hued black for the cursor and text selection
cursor #2E1505
cursor_text_color #ffffff
selection_background #2E1505
selection_foreground #ffffff

# Disable the annoying close confirmation
confirm_os_window_close 0

# Wayland specific
linux_display_server wayland