configuration {
    modi: "drun";
    show-icons: true;
    font: "Adwaita Mono Nerd Font 12";
}

@theme "/dev/null"

* {
    bg-col:  #000000;
    border-col: #2E1505; /* Orange-hued black border */
    selected-col: #2E1505; /* Orange-hued black selection */
    fg-col: #ffffff;
    width: 600;
}

window {
    padding: 20px;
    background-color: @bg-col;
    border: 2px;
    border-color: @border-col;
    border-radius: 0px; /* Sharp corners */
}

mainbox {
    background-color: @bg-col;
}

inputbar {
    children: [prompt,entry];
    background-color: @bg-col;
    padding: 2px;
}

prompt {
    background-color: @bg-col;
    padding: 6px;
    text-color: @fg-col;
    margin: 20px 0px 0px 20px;
}

entry {
    padding: 6px;
    margin: 20px 0px 0px 10px;
    text-color: @fg-col;
    background-color: @bg-col;
}

listview {
    border: 0px;
    padding: 6px 0px 0px;
    margin: 10px 0px 0px 20px;
    columns: 1;
    lines: 5;
    background-color: @bg-col;
}

element {
    padding: 10px;
    background-color: @bg-col;
    text-color: @fg-col;
    border-radius: 0px; /* Sharp corners */
}

element-icon {
    size: 25px;
}

element selected {
    background-color: @selected-col;
    text-color: @fg-col;
    border: 1px solid @border-col;
}